# Problem
# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number
# of times that the symbols 'A', 'C', 'G', and 'T' occur in s.


def count_nuc(s):
    s = s.upper()
    counter_a = 0
    counter_c = 0
    counter_g = 0
    counter_t = 0
    for char in s:
        if char == 'A':
            counter_a += 1
        elif char == 'C':
            counter_c += 1
        elif char == 'G':
            counter_g += 1
        elif char == 'T':
            counter_t += 1
        else:
            print("Wrong nuc: " + char)

    return str(counter_a) + " " + str(counter_c) + " " + str(counter_g) + " " + str(counter_t)

seq = "GGTCCGGTACTTGACAGGAGGACACCCACCCTTAGCCAAACTAAACGCCAGCCTTGATTGAGTCAGTTCAATACTTATGTTGAGGGTGAATGTAACCTTAGAATGCCAACGCGCGAACAGACACGTCACGGTTGGTAGAGGCGTCGCATCGCGCTTAATCGCTATACCCCGTCGCTCCTTTGGTTTCCTTCTAACAGCACTTTGTCCATCGCCTTCTTATAGGATTGCGACGGCGTGATGCTCCCTAGTATCGAATAATTACCTCTTGAACACTTAGAAATGTTCGGCTGTCTATCCACTGAAGTCCAACCATGGAATGGTAGAAGCTGAATATCAAACCTGGAGCTTTGTTTGGTTGGAGCAAGGAGATCCCTTCCTATAATGGTACTTAACTGTGTGGAAGGTCAATCAGCCGACATAATCCCTTCTCCGCTAATCCATCATGTCTAGAGCGTAGTCTGGAGCAGCCTAGGTCTCTCGGTAACCCGCTAAGTCCACTGCCTGATGCATACGTCATCTGATTTCCTGGCATCGTGTGCATTCGCAATTCCTCCAGCTGTTATCAAACCAGCTGTGCCTTGTTCGCCATTCAAGACGGTAGGAAAGGCCCGTAATATGGCTCACCAGTAGACATCGCTCCCCTCGCTGGACTTTTTGACCACAGGAAAGGTCACTAGCCCTGTCTTGCATTTCTAATTTTACTTCATCGGATGAGGGAGCCTCCATTCTATTGTCACAGGCCCGAGGTGCCTAAAGATATATGAGTGCGGTGAATGCAAATTCACCACTGTGTGTCCACGCGTAAGGGCTTGGTATGCCATCCGGAATATCTAGACATGGATAACCCGTCGTGAGAGGACATACGCCCCGTCGTAAGGGTTTTTGCCTCTCCCCGTCTTAACAGCGTGTTATGTCCTTCATGTAAGGTGCACCAAGAAAGTCGCCGGTATATTCTGCCCAGCTTAATTCACGTCCGACTGTAACTCGATCCATA"
print(count_nuc(seq))

