# Problem
# Given: Two DNA strings s and t (each of length at most 1 kbp).
# Return: All locations of t as a substring of s.

def motif_finding(s, t):
    len_of_motif = len(t)
    indexes = []

    for i in range(len(s)):
        if s[i:i + len_of_motif] == t:
            indexes.append(i + 1)  # index starts with 1 for output

    # print
    for index in indexes:
        print(index, end=" ")


seq = "TTAAGATCATATAAGATCAAAGATCACGAAGATCAGTAAGATCATGATACAAGATCACAAAGATCAAACTAAGATCAAAGATCAAAGATCAAACAAGATCATGCTTAAGATCACAATCCTTGAAGATCAAGTGAAGATCACTAAAGATCACATTGTTTAAGATCAGCTCGTGATGTGTGGAAGATCAGAAGATCATAAGATCACGTCTCATATTACGGGAAGATCAGCTTCATTCAAGATCAAAAGATCAGAAGATCAAAGATCAAAAGATCAGCATAAGATCAGAAGATCATAAGATCAAAGATCAGAAGATCAGAATATGTCAAGATCACAGTCTATCCTTGTAAGATCAAAGATCAAAGATCATAAGATCACGCAAAGATCAGCTAAGATCAATTCGGTAAGATCATAAGATCACGGAGGAAGATCAGAAAGATCAAAGATCAAAGATCACTAAAGATCAAAAAGATCACCCTGAAGATCATCATAAGATCACCGACGTGAAAGATCACAAGATCATGAAGATCAAAAGATCACCGTGCTCTCAGCCAAGATCAAAAGATCAAAGATCATGGGACCGAAGATCATTTCAAAGATCAGCAAGATCAGAAGATCAGCGAACAAGATCAAAGATCATAAGATCAAAGATCAAAGATCACAAGATCAGTTAAGATCACACAAGATCAAAGATCAGAAGGAAGATCACTTAAGATCATCAAGATCACGGAAAAGATCATACCTTGAAAGATCAAAGATCAGAAGATCAAAAGATCAAAGATCAAAGATCAAGTCAAGATCAAAGATCAACCAAAAAAGATCACAGTAAAGATCAGAAGATCAGAAGATCAGATAAGATCAAAGATCACAAGATCAAATGCCCAAGATCACAAGATCAGGGCGGATTAAAGATCACAACTGAAGATCACA"
motif = "AAGATCAAA"
motif_finding(seq, motif)
