# Problem
# Given: {DNA strings}} Text and Pattern.
# Return: Count(Text, Pattern).

# pseudo code:
# PatternCount(Text, Pattern)
#         count ← 0
#         for i ← 0 to |Text| − |Pattern|
#             if Text(i, |Pattern|) = Pattern
#                 count ← count + 1
#         return count

def pattern_count(text, pattern):
    # count = 0
    # for i in range(len(text) - len(pattern)):
    #     if text[i: i + len(pattern)] == pattern:
    #         print(text[i: i + len(pattern)])
    #         count = count + 1
    return text.count(pattern)


input_text = "TTGCTCTATCATGCTCTATCTAGCTCTATGTGGCTCTATGGCTCTATGCAAGCTCTATATGCTCTATTTCGCTCTATAAGCTCTATGCTCTATGGGCTCTATGTTAAATGACAGTGCTCTATCCTGCTCTATGCTCTATGGATCTAGCTCTATATGCGCTCTATCGCTCTATGGCTCTATGCTAAGTTGCTCTATGGCTCTATAAGCTCGCTCTATTACTGGCAGCTCTATCGAGCTCTATTCGAGCTCTATTTCTCGGCTCTATGCTCTATTGCTCTATGCGCTCTATTCTGAGCTTTAACGGCTCTATCGACGCTCTATGACGCTCTATGCTCTATCGAGCTCTATGCTCTATAGCGGCTCTATCATGCTCTATTGACCGCACGGCCCCTGCTCTATGAGTGCTCTATAAGCTCTATGACGGTTCACCCGGCTCTATTAAGTGCTCTATCGAAGGCTCTATCGCTCTATGTGTGGCTCTATTTGGCGCTCTATTGATGCTCTATTGGCTCTATGGCTCTATTAGCTCTATGGATCGAGCTCTATGCTCTATGGGCTCTATTTCGCTCTATGCTCTATGCTCTATTCAGGCTCTATCCTGCTCTATCCTCGCTCTATCGCTCTATAACGCGCACGAATGTTGGCTCTATACGGCTCTATGGGCTCTATCGTGCTCTATCACCCGCTCGCTCTATACGCGCTCTATGGCTGCTCTATCGCTCTATGGCGACGCTCTATCTGCTCTATACGGCTCTATTGCTCTATTGTGCAAGATGGCTCTATTTGCTCTATGTTCCGTACGCTCTATGGCTCTATTTGGCTCTATATATTCACACGCTCTATGCTCTATAGCTCTATGTAGCTCTATGCTCTATATTCAACTGGCTCTATCGCTCTATGCTCTATGCAGTGCTCTATAGCTCTATTGCTCTATCGTAATC"
input_pattern = "GCTCTATGC"
print(pattern_count(input_text, input_pattern))
